VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClassEvent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public WithEvents Container As VBControlExtender
Attribute Container.VB_VarHelpID = -1

Public Index As Long
Public Master As FormMain

Private Sub Container_ObjectEvent(Info As EventInfo)
        Call Master.EventManage(Me, Info)
End Sub


